# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aces', '0003_auto_20160825_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('no_of_slots', models.IntegerField()),
                ('no_of_available_slots', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aces.Slot'),
        ),
    ]
